version: '3.8'

services:
    tutorial:
        image: parledoct/tutorials:base
        volumes:
            - .:/parledoct-tutorials
        working_dir: /parledoct-tutorials
        ports:
            - "8888:8888"
